#!/usr/bin/env python3
"""
Encode a binary AndroidManifest.xml (Android's AXML format) without aapt2.

Android does not read the textual AndroidManifest.xml from an APK; it reads a
compiled binary-XML resource. Normally aapt2 produces it, but the Android SDK
build tools are not available in this environment, so we emit the chunk format
directly. Framework attribute / resource IDs are read from ids.properties,
which is generated by running DumpIds against android.jar.

Usage: make_manifest.py ids.properties out/AndroidManifest.xml
"""
import struct
import sys

ANDROID_NS = "http://schemas.android.com/apk/res/android"

# Res_value data types
T_REF = 0x01
T_STRING = 0x03
T_INT_DEC = 0x10
T_INT_BOOL = 0x12

# android:configChanges flag bits (stable framework constants)
CONFIG = {
    "orientation": 0x0080,
    "screenSize": 0x0400,
    "keyboardHidden": 0x0020,
    "screen": 0x0400,
}
# android:screenOrientation enum
ORIENT_PORTRAIT = 0x0001


def load_ids(path):
    ids = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or "=" not in line:
                continue
            k, v = line.split("=", 1)
            ids[k.strip()] = int(v.strip())
    return ids


class Val:
    __slots__ = ("dtype", "data", "raw")

    def __init__(self, dtype, data, raw=None):
        self.dtype = dtype
        self.data = data & 0xFFFFFFFF
        self.raw = raw  # string for T_STRING values


def s(text):
    return Val(T_STRING, 0, text)


def i(n):
    return Val(T_INT_DEC, n & 0xFFFFFFFF)


def b(flag):
    return Val(T_INT_BOOL, 0xFFFFFFFF if flag else 0)


def ref(resid):
    return Val(T_REF, resid)


def build_tree(ids):
    """Return (events) describing the manifest. Attributes: (ns, name, resid, Val).
    resid is None for non-resource attributes (e.g. package)."""
    A = ANDROID_NS

    def a(name, resid_key, val):
        return (A, name, ids[resid_key], val)

    def order(attrs):
        # aapt orders attributes with resource IDs ascending, then the
        # non-resource attributes (e.g. package). obtainStyledAttributes
        # relies on the resource-id ones being sorted.
        with_id = sorted([t for t in attrs if t[2] is not None], key=lambda t: t[2])
        without = [t for t in attrs if t[2] is None]
        return with_id + without

    manifest_attrs = [
        (None, "package", None, s("com.nova.blocks")),
        a("versionCode", "attr.versionCode", i(1)),
        a("versionName", "attr.versionName", s("1.0")),
    ]
    uses_sdk_attrs = [
        a("minSdkVersion", "attr.minSdkVersion", i(24)),
        a("targetSdkVersion", "attr.targetSdkVersion", i(34)),
    ]
    application_attrs = [
        a("label", "attr.label", s("Nova 2048")),
        a("icon", "attr.icon", ref(ids["res.icon"])),
        a("theme", "attr.theme", ref(ids["res.theme"])),
        a("hardwareAccelerated", "attr.hardwareAccelerated", b(True)),
    ]
    cfg = CONFIG["orientation"] | CONFIG["screenSize"] | CONFIG["keyboardHidden"]
    activity_attrs = [
        a("name", "attr.name", s("com.nova.blocks.MainActivity")),
        a("exported", "attr.exported", b(True)),
        a("configChanges", "attr.configChanges", i(cfg)),
        a("screenOrientation", "attr.screenOrientation", i(ORIENT_PORTRAIT)),
    ]
    action_attrs = [a("name", "attr.name", s("android.intent.action.MAIN"))]
    category_attrs = [a("name", "attr.name", s("android.intent.category.LAUNCHER"))]

    ev = []
    ev.append(("startns", "android", A))
    ev.append(("start", None, "manifest", order(manifest_attrs)))
    ev.append(("start", None, "uses-sdk", order(uses_sdk_attrs)))
    ev.append(("end", None, "uses-sdk"))
    ev.append(("start", None, "application", order(application_attrs)))
    ev.append(("start", None, "activity", order(activity_attrs)))
    ev.append(("start", None, "intent-filter", []))
    ev.append(("start", None, "action", order(action_attrs)))
    ev.append(("end", None, "action"))
    ev.append(("start", None, "category", order(category_attrs)))
    ev.append(("end", None, "category"))
    ev.append(("end", None, "intent-filter"))
    ev.append(("end", None, "activity"))
    ev.append(("end", None, "application"))
    ev.append(("end", None, "manifest"))
    ev.append(("endns", "android", A))
    return ev


class StringPool:
    def __init__(self):
        self.strings = []
        self.index = {}
        self.resmap = []  # resource ids parallel to first len(resmap) strings

    def add(self, text):
        if text is None:
            return 0xFFFFFFFF
        if text in self.index:
            return self.index[text]
        idx = len(self.strings)
        self.strings.append(text)
        self.index[text] = idx
        return idx

    def add_resid_attrs(self, pairs):
        # pairs: list of (name, resid) sorted; must be the FIRST strings.
        for name, resid in pairs:
            assert name not in self.index, name
            self.index[name] = len(self.strings)
            self.strings.append(name)
            self.resmap.append(resid)


def collect_resid_attrs(events):
    seen = {}
    for e in events:
        if e[0] == "start":
            for (ns, name, resid, val) in e[3]:
                if resid is not None:
                    if name in seen:
                        assert seen[name] == resid
                    else:
                        seen[name] = resid
    return sorted(seen.items(), key=lambda kv: kv[1])


def encode_string_pool(pool):
    # UTF-16LE strings, flags = 0
    data = bytearray()
    offsets = []
    for text in pool.strings:
        offsets.append(len(data))
        u = text.encode("utf-16-le")
        n = len(text)  # code units (BMP only here)
        data += struct.pack("<H", n)
        data += u
        data += b"\x00\x00"
    # pad string data to 4 bytes
    while len(data) % 4 != 0:
        data += b"\x00"

    string_count = len(pool.strings)
    header_size = 28
    strings_start = header_size + 4 * string_count
    chunk_size = strings_start + len(data)

    out = bytearray()
    out += struct.pack("<HH", 0x0001, header_size)      # type, headerSize
    out += struct.pack("<I", chunk_size)                 # size
    out += struct.pack("<I", string_count)               # stringCount
    out += struct.pack("<I", 0)                           # styleCount
    out += struct.pack("<I", 0)                           # flags (UTF-16)
    out += struct.pack("<I", strings_start)               # stringsStart
    out += struct.pack("<I", 0)                           # stylesStart
    for off in offsets:
        out += struct.pack("<I", off)
    out += data
    assert len(out) == chunk_size
    return bytes(out)


def encode_resource_map(pool):
    ids = pool.resmap
    size = 8 + 4 * len(ids)
    out = bytearray()
    out += struct.pack("<HH", 0x0180, 8)   # type, headerSize
    out += struct.pack("<I", size)
    for rid in ids:
        out += struct.pack("<I", rid)
    return bytes(out)


def encode_value(pool, val):
    if val.dtype == T_STRING:
        sidx = pool.add(val.raw)
        raw = sidx
        data = sidx
    else:
        raw = 0xFFFFFFFF
        data = val.data
    # Res_value: size(2)=8, res0(1)=0, dataType(1), data(4)
    return raw, struct.pack("<HBBI", 8, 0, val.dtype, data & 0xFFFFFFFF)


def encode_nodes(pool, events):
    out = bytearray()
    line = 1
    for e in events:
        kind = e[0]
        if kind == "startns" or kind == "endns":
            _, prefix, uri = e
            typ = 0x0100 if kind == "startns" else 0x0101
            p = pool.add(prefix)
            u = pool.add(uri)
            out += struct.pack("<HH", typ, 16)
            out += struct.pack("<I", 24)          # size
            out += struct.pack("<I", line)
            out += struct.pack("<I", 0xFFFFFFFF)  # comment
            out += struct.pack("<II", p, u)
        elif kind == "start":
            _, ns, name, attrs = e
            ns_idx = pool.add(ns) if ns is not None else 0xFFFFFFFF
            name_idx = pool.add(name)
            attr_blob = bytearray()
            for (ans, aname, resid, val) in attrs:
                a_ns = pool.add(ans) if ans is not None else 0xFFFFFFFF
                a_name = pool.add(aname)
                raw, resval = encode_value(pool, val)
                attr_blob += struct.pack("<III", a_ns, a_name, raw & 0xFFFFFFFF)
                attr_blob += resval
            count = len(attrs)
            size = 16 + 20 + len(attr_blob)
            out += struct.pack("<HH", 0x0102, 16)
            out += struct.pack("<I", size)
            out += struct.pack("<I", line)
            out += struct.pack("<I", 0xFFFFFFFF)          # comment
            out += struct.pack("<II", ns_idx, name_idx)   # attrExt ns, name
            out += struct.pack("<HH", 20, 20)             # attributeStart, attributeSize
            out += struct.pack("<HH", count, 0)           # attributeCount, idIndex
            out += struct.pack("<HH", 0, 0)               # classIndex, styleIndex
            out += attr_blob
        elif kind == "end":
            _, ns, name = e
            ns_idx = pool.add(ns) if ns is not None else 0xFFFFFFFF
            name_idx = pool.add(name)
            out += struct.pack("<HH", 0x0103, 16)
            out += struct.pack("<I", 24)
            out += struct.pack("<I", line)
            out += struct.pack("<I", 0xFFFFFFFF)
            out += struct.pack("<II", ns_idx, name_idx)
        line += 1
    return bytes(out)


def main():
    ids_path, out_path = sys.argv[1], sys.argv[2]
    ids = load_ids(ids_path)
    events = build_tree(ids)

    pool = StringPool()
    # 1) resid-bearing attribute names first (parallel to resource map)
    pool.add_resid_attrs(collect_resid_attrs(events))

    # 2) node encoding also registers remaining strings (ns, names, values)
    node_bytes = encode_nodes(pool, events)

    # 3) now that the pool is complete, encode pool + resmap
    pool_bytes = encode_string_pool(pool)
    resmap_bytes = encode_resource_map(pool)

    body = pool_bytes + resmap_bytes + node_bytes
    total = 8 + len(body)
    header = struct.pack("<HH", 0x0003, 8) + struct.pack("<I", total)
    with open(out_path, "wb") as f:
        f.write(header + body)
    print("wrote %s (%d bytes, %d strings, %d resmap)" %
          (out_path, total, len(pool.strings), len(pool.resmap)))


if __name__ == "__main__":
    main()
